name: cache

on:
  workflow_dispatch:

jobs:
  test_cache:
    name: job to test cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/cache@v6
        id: generateCache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - name: confirm cache
        if: steps.generateCache.outputs.cache-hit == 'true'
        run: echo cache entry found!
